name: sonanceep_sns
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.3.2
  firebase_core: ^2.15.1  # firebase_core: ^2.11.0
  firebase_auth: ^4.9.0  # firebase_auth: ^4.4.0
  cloud_firestore: ^4.8.2
  firebase_analytics: ^10.4.5  # firebase_analytics: ^10.2.0
  google_fonts: ^4.0.3
  pull_to_refresh: ^2.0.0
  image_cropper: ^1.4.1  # image_cropper: ^3.0.3
  shared_preferences: ^2.1.0
  url_launcher: ^6.1.10
  clipboard: ^0.1.3
  flutter_launcher_icons: ^0.12.0
  flash: ^3.0.5  # flash: ^2.0.3+3
  uuid: ^3.0.7
  image_picker: ^0.8.7+1
  video_player: ^2.7.0
  chewie: ^1.7.0
  just_audio: ^0.9.32
  flutter_svg: ^2.0.4
  firebase_storage: ^11.2.6  # firebase_storage: ^11.1.0
  firebase_crashlytics: ^3.3.5  # firebase_crashlytics: ^3.3.3
  fluttertoast: ^8.2.1
  intl: ^0.18.1
  freezed_annotation: ^2.2.0
  material_floating_search_bar_2: ^0.5.0  # material_floating_search_bar: ^0.3.7
  http: ^0.13.5
  flutter_dotenv: ^5.1.0
  algolia: ^1.1.2
  hooks_riverpod: ^2.3.6
  flutter_hooks: ^0.18.6
  grpc: ^3.2.4
  protoc_plugin: ^21.1.1

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  freezed: ^2.3.2
  json_serializable: ^6.6.1
  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  generate: true
  uses-material-design: true

  assets:
   - .env





















# name: sonanceep_sns
# description: A new Flutter project.

# publish_to: 'none'

# version: 1.0.0+1

# environment:
#   sdk: '>=2.19.5 <3.0.0'

# dependencies:
#   flutter:
#     sdk: flutter

#   cupertino_icons: ^1.0.2
#   flutter_riverpod: ^2.3.2
#   firebase_core: ^2.11.0
#   firebase_auth: ^4.4.0
#   cloud_firestore: ^4.8.2
#   firebase_analytics: ^10.2.0
#   google_fonts: ^4.0.3
#   pull_to_refresh: ^2.0.0
#   image_cropper: ^1.4.1  # image_cropper: ^3.0.3
#   shared_preferences: ^2.1.0
#   url_launcher: ^6.1.10
#   clipboard: ^0.1.3
#   flutter_launcher_icons: ^0.12.0
#   flash: ^3.0.5+1  # flash: ^2.0.3+3
#   uuid: ^3.0.7
#   image_picker: ^0.8.7+1
#   video_player: ^2.7.0
#   chewie: ^1.7.0
#   just_audio: ^0.9.32
#   flutter_svg: ^2.0.4
#   firebase_storage: ^11.2.6  # firebase_storage: ^11.1.0
#   firebase_crashlytics: ^3.3.5  # firebase_crashlytics: ^3.3.3
#   fluttertoast: ^8.2.1
#   intl: ^0.18.1
#   freezed_annotation: ^2.2.0
#   material_floating_search_bar: ^0.3.7
#   http: ^0.13.5
#   flutter_dotenv: ^5.1.0
#   algolia: ^1.1.2
#   hooks_riverpod: ^2.3.6
#   flutter_hooks: ^0.18.6

#   flutter_localizations:
#     sdk: flutter

# dev_dependencies:
#   freezed: ^2.3.2
#   json_serializable: ^6.6.1
#   build_runner: ^2.3.3
#   flutter_test:
#     sdk: flutter
#   flutter_lints: ^2.0.0

# flutter:
#   generate: true
#   uses-material-design: true

#   assets:
#    - .env