// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAV-kyq6zXWjJuL2IyABYQ_9KXyvqkt8V8',
    appId: '1:837109495001:web:bb60a5b12d5596792d7ac8',
    messagingSenderId: '837109495001',
    projectId: 'sonanceep-sns',
    authDomain: 'sonanceep-sns.firebaseapp.com',
    storageBucket: 'sonanceep-sns.appspot.com',
    measurementId: 'G-5Y3Y9NXG04',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmEb0WurRz2d3BV4U1Uw38OanKoP0pZVU',
    appId: '1:837109495001:android:bc0a25ed9e6ad10a2d7ac8',
    messagingSenderId: '837109495001',
    projectId: 'sonanceep-sns',
    storageBucket: 'sonanceep-sns.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4aeGuyydOC1Od88_W_cP9Bmo9srzwSm8',
    appId: '1:837109495001:ios:438ec84d322680242d7ac8',
    messagingSenderId: '837109495001',
    projectId: 'sonanceep-sns',
    storageBucket: 'sonanceep-sns.appspot.com',
    iosClientId: '837109495001-p6pdl2343uep5qd1f0io1uta8mq9njop.apps.googleusercontent.com',
    iosBundleId: 'com.example.sonanceepSns',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4aeGuyydOC1Od88_W_cP9Bmo9srzwSm8',
    appId: '1:837109495001:ios:438ec84d322680242d7ac8',
    messagingSenderId: '837109495001',
    projectId: 'sonanceep-sns',
    storageBucket: 'sonanceep-sns.appspot.com',
    iosClientId: '837109495001-p6pdl2343uep5qd1f0io1uta8mq9njop.apps.googleusercontent.com',
    iosBundleId: 'com.example.sonanceepSns',
  );
}
